//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    [DefaultProperty("ThoiGian")]
    public partial class BAOHANH : DevExpress.Persistent.BaseImpl.BaseObject
    {
        DateTime fThoiGian;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ThoiGian
        {
            get { return fThoiGian; }
            set { SetPropertyValue<DateTime>(nameof(ThoiGian), ref fThoiGian, value); }
        }
        [Association(@"SANPHAMReferencesBAOHANH"), Aggregated]
        public XPCollection<SANPHAM> SANPHAMs { get { return GetCollection<SANPHAM>(nameof(SANPHAMs)); } }
    }

}
