//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    public partial class CHAMCONG : XPObject
    {
        NHANVIEN fID_NHANVIEN;
        [Association(@"CHAMCONGReferencesNHANVIEN")]
        public NHANVIEN ID_NHANVIEN
        {
            get { return fID_NHANVIEN; }
            set { SetPropertyValue<NHANVIEN>(nameof(ID_NHANVIEN), ref fID_NHANVIEN, value); }
        }
        DateTime fGioVao;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime GioVao
        {
            get { return fGioVao; }
            set { SetPropertyValue<DateTime>(nameof(GioVao), ref fGioVao, value); }
        }
        DateTime fGioRa;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime GioRa
        {
            get { return fGioRa; }
            set { SetPropertyValue<DateTime>(nameof(GioRa), ref fGioRa, value); }
        }
    }

}
