//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    [DefaultProperty("SoLuong")]
    public partial class CTHD : DevExpress.Persistent.BaseImpl.BaseObject
    {
        SANPHAM fID_SANPHAM;
        [Association(@"CTHDReferencesSANPHAM")]
        public SANPHAM ID_SANPHAM
        {
            get { return fID_SANPHAM; }
            set { SetPropertyValue<SANPHAM>(nameof(ID_SANPHAM), ref fID_SANPHAM, value); }
        }
        string fSoLuong;
        public string SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<string>(nameof(SoLuong), ref fSoLuong, value); }
        }
        string fDonGia;
        public string DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<string>(nameof(DonGia), ref fDonGia, value); }
        }
        string fThanhTien;
        public string ThanhTien
        {
            get { return fThanhTien; }
            set { SetPropertyValue<string>(nameof(ThanhTien), ref fThanhTien, value); }
        }
    }

}
