//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    [DefaultProperty("NgayHetHan")]
    public partial class DONBAOHANH : DevExpress.Persistent.BaseImpl.BaseObject
    {
        PHIEUBAOHANH fID_PHIEUBAOHANH;
        [Association(@"DONBAOHANHReferencesPHIEUBAOHANH")]
        public PHIEUBAOHANH ID_PHIEUBAOHANH
        {
            get { return fID_PHIEUBAOHANH; }
            set { SetPropertyValue<PHIEUBAOHANH>(nameof(ID_PHIEUBAOHANH), ref fID_PHIEUBAOHANH, value); }
        }
        DateTime fNgayHetHan;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime NgayHetHan
        {
            get { return fNgayHetHan; }
            set { SetPropertyValue<DateTime>(nameof(NgayHetHan), ref fNgayHetHan, value); }
        }
        string fSoPhieu;
        [Size(50)]
        public string SoPhieu
        {
            get { return fSoPhieu; }
            set { SetPropertyValue<string>(nameof(SoPhieu), ref fSoPhieu, value); }
        }
    }

}
