//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    [DefaultProperty("SoLuong")]
    public partial class DONGNHAP : DevExpress.Persistent.BaseImpl.BaseObject
    {
        PHIEUNHAP fID_PHIEUNHAP;
        [Association(@"DONGNHAPReferencesPHIEUNHAP")]
        public PHIEUNHAP ID_PHIEUNHAP
        {
            get { return fID_PHIEUNHAP; }
            set { SetPropertyValue<PHIEUNHAP>(nameof(ID_PHIEUNHAP), ref fID_PHIEUNHAP, value); }
        }
        SANPHAM fID_SANPHAM;
        [Association(@"DONGNHAPReferencesSANPHAM")]
        public SANPHAM ID_SANPHAM
        {
            get { return fID_SANPHAM; }
            set { SetPropertyValue<SANPHAM>(nameof(ID_SANPHAM), ref fID_SANPHAM, value); }
        }
        string fSoLuong;
        [Size(50)]
        public string SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<string>(nameof(SoLuong), ref fSoLuong, value); }
        }
        string fDonGia;
        public string DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<string>(nameof(DonGia), ref fDonGia, value); }
        }
    }

}
