//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    [DefaultProperty("NgayTao")]
    public partial class DONVANCHUYEN : DevExpress.Persistent.BaseImpl.BaseObject
    {
        DONHANG fID_DONHANG;
        public DONHANG ID_DONHANG
        {
            get { return fID_DONHANG; }
            set { SetPropertyValue<DONHANG>(nameof(ID_DONHANG), ref fID_DONHANG, value); }
        }
        DateTime fNgayTao;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime NgayTao
        {
            get { return fNgayTao; }
            set { SetPropertyValue<DateTime>(nameof(NgayTao), ref fNgayTao, value); }
        }
        string fTrangThai;
        [Size(50)]
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
        [Association(@"DONVANCHUYENReferencesDONHANG")]
        public XPCollection<DONHANG> DONHANGs { get { return GetCollection<DONHANG>(nameof(DONHANGs)); } }
    }

}
