//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    [DefaultProperty("TenNCC")]
    public partial class NCC : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fTenNCC;
        [Size(50)]
        public string TenNCC
        {
            get { return fTenNCC; }
            set { SetPropertyValue<string>(nameof(TenNCC), ref fTenNCC, value); }
        }
        string fSoDT;
        public string SoDT
        {
            get { return fSoDT; }
            set { SetPropertyValue<string>(nameof(SoDT), ref fSoDT, value); }
        }
        string fDiaChi;
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        [Association(@"PHIEUNHAPReferencesNCC"), Aggregated]
        public XPCollection<PHIEUNHAP> PHIEUNHAPs { get { return GetCollection<PHIEUNHAP>(nameof(PHIEUNHAPs)); } }
        [Association(@"PHIEUCHIReferencesNCC"), Aggregated]
        public XPCollection<PHIEUCHI> PHIEUCHIs { get { return GetCollection<PHIEUCHI>(nameof(PHIEUCHIs)); } }
        [Association(@"DANHMUCReferencesNCC"), Aggregated]
        public XPCollection<DANHMUC> DANHMUCs { get { return GetCollection<DANHMUC>(nameof(DANHMUCs)); } }
    }

}
