//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    [DefaultProperty("So")]
    public partial class PHIEUCHI : DevExpress.Persistent.BaseImpl.BaseObject
    {
        NHANVIEN fID_NHANVIEN;
        [Association(@"PHIEUCHIReferencesNHANVIEN")]
        public NHANVIEN ID_NHANVIEN
        {
            get { return fID_NHANVIEN; }
            set { SetPropertyValue<NHANVIEN>(nameof(ID_NHANVIEN), ref fID_NHANVIEN, value); }
        }
        NCC fID_NCC;
        [Association(@"PHIEUCHIReferencesNCC")]
        public NCC ID_NCC
        {
            get { return fID_NCC; }
            set { SetPropertyValue<NCC>(nameof(ID_NCC), ref fID_NCC, value); }
        }
        string fSo;
        public string So
        {
            get { return fSo; }
            set { SetPropertyValue<string>(nameof(So), ref fSo, value); }
        }
        DateTime fNgay;
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        string fTongTien;
        public string TongTien
        {
            get { return fTongTien; }
            set { SetPropertyValue<string>(nameof(TongTien), ref fTongTien, value); }
        }
    }

}
