//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CNPM_PKDT.Module.database
{

    [DefaultProperty("TenSP")]
    public partial class SANPHAM : DevExpress.Persistent.BaseImpl.BaseObject
    {
        DANHMUC fID_DANHMUC;
        [Association(@"SANPHAMReferencesDANHMUC")]
        public DANHMUC ID_DANHMUC
        {
            get { return fID_DANHMUC; }
            set { SetPropertyValue<DANHMUC>(nameof(ID_DANHMUC), ref fID_DANHMUC, value); }
        }
        BAOHANH fID_BAOHANH;
        [Association(@"SANPHAMReferencesBAOHANH")]
        public BAOHANH ID_BAOHANH
        {
            get { return fID_BAOHANH; }
            set { SetPropertyValue<BAOHANH>(nameof(ID_BAOHANH), ref fID_BAOHANH, value); }
        }
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fDVT;
        public string DVT
        {
            get { return fDVT; }
            set { SetPropertyValue<string>(nameof(DVT), ref fDVT, value); }
        }
        decimal fGiaBan;
        public decimal GiaBan
        {
            get { return fGiaBan; }
            set { SetPropertyValue<decimal>(nameof(GiaBan), ref fGiaBan, value); }
        }
        string fTonKho;
        public string TonKho
        {
            get { return fTonKho; }
            set { SetPropertyValue<string>(nameof(TonKho), ref fTonKho, value); }
        }
        [Association(@"CTHDReferencesSANPHAM"), Aggregated]
        public XPCollection<CTHD> CTHDs { get { return GetCollection<CTHD>(nameof(CTHDs)); } }
        [Association(@"DONGNHAPReferencesSANPHAM"), Aggregated]
        public XPCollection<DONGNHAP> DONGNHAPs { get { return GetCollection<DONGNHAP>(nameof(DONGNHAPs)); } }
    }

}
